"""Back ends: SVG and TikZ, both drawn from the same primitive list.

Because the layout is resolved to explicit coordinates before either back end
runs, the TikZ output is plain `\\draw` commands. It needs only the tikz
package (no circuitikz) and compiles to exactly what the SVG shows.
"""
from __future__ import annotations

from html import escape

from .geom import Circle, Line, Path, Poly, Text
from .markup import parse as parse_markup, to_tex

SVG_UNIT = 20        # px per grid unit
FONT_PX = 13


def _f(v):
    s = f"{v:.3f}".rstrip("0").rstrip(".")
    return "0" if s == "-0" else s


# --- SVG ------------------------------------------------------------------------

def to_svg(drawing, unit=SVG_UNIT, background="white"):
    x0, y0, x1, y1 = drawing.bbox
    W, H = (x1 - x0) * unit, (y1 - y0) * unit
    P = lambda p: f"{_f((p[0] - x0) * unit)},{_f((p[1] - y0) * unit)}"
    sw = 1.4
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{_f(W)}" height="{_f(H)}" '
           f'viewBox="0 0 {_f(W)} {_f(H)}" font-family="\'Latin Modern Roman\', \'CMU Serif\', '
           f'\'Times New Roman\', serif" font-size="{FONT_PX}">']
    if drawing.title:
        out.append(f"<title>{escape(drawing.title)}</title>")
    if background:
        out.append(f'<rect width="100%" height="100%" fill="{background}"/>')
    out.append(f'<g stroke="black" stroke-width="{sw}" fill="none" '
               f'stroke-linecap="round" stroke-linejoin="round">')
    for p in drawing.prims:
        if isinstance(p, Line):
            attrs = ""
            if p.dashed:
                attrs += ' stroke-dasharray="5,4"'
            if p.color:
                attrs += f' stroke="{p.color}"'
            if p.width != 1.0:
                attrs += f' stroke-width="{_f(sw * p.width)}"'
            pts = " ".join(P(q) for q in p.pts)
            out.append(f'<polyline points="{pts}"{attrs}/>')
        elif isinstance(p, Poly):
            pts = " ".join(P(q) for q in p.pts)
            fill = f' fill="{p.fill}"' if p.fill != "none" else ""
            out.append(f'<polygon points="{pts}"{fill}/>')
        elif isinstance(p, Circle):
            cx, cy = P(p.c).split(",")
            fill = f' fill="{p.fill}"' if p.fill != "none" else ""
            if p.fill == "black" and p.r < 0.2:
                fill += ' stroke="none"'
            out.append(f'<circle cx="{cx}" cy="{cy}" r="{_f(p.r * unit)}"{fill}/>')
        elif isinstance(p, Path):
            d = f"M{P(p.start)}"
            for c1, c2, e in p.segs:
                d += f" C{P(c1)} {P(c2)} {P(e)}"
            if p.closed:
                d += " Z"
            fill = f' fill="{p.fill}"' if p.fill != "none" else ""
            out.append(f'<path d="{d}"{fill}/>')
    out.append("</g>")
    for p in drawing.prims:
        if isinstance(p, Text):
            out.append(_svg_text(p, P, unit))
    out.append("</svg>")
    return "\n".join(out)


def _svg_text(t, P, unit):
    x, y = P(t.pos).split(",")
    a = t.anchor
    anchor = "start" if "w" in a else "end" if "e" in a else "middle"
    # vertical: dominant-baseline is unreliable across viewers, use dy
    size = FONT_PX * t.size
    if "n" in a:
        dy = size * 0.80
    elif "s" in a:
        dy = -size * 0.22
    else:
        dy = size * 0.30
    spans = []
    for text, style in parse_markup(t.s):
        s = escape(text)
        if style == "sub":
            spans.append(f'<tspan baseline-shift="-25%" font-size="{_f(size * 0.72)}">{s}</tspan>')
        elif style == "sup":
            spans.append(f'<tspan baseline-shift="40%" font-size="{_f(size * 0.72)}">{s}</tspan>')
        elif style == "over":
            spans.append(f'<tspan text-decoration="overline">{s}</tspan>')
        else:
            spans.append(f"<tspan>{s}</tspan>")
    fs = f' font-size="{_f(size)}"' if t.size != 1.0 else ""
    return (f'<text x="{x}" y="{_f(float(y) + dy)}" text-anchor="{anchor}"{fs} '
            f'fill="black" stroke="none">{"".join(spans)}</text>')


# --- TikZ ------------------------------------------------------------------------

TIKZ_ANCHOR = {"c": "center", "n": "north", "s": "south", "e": "east", "w": "west",
               "ne": "north east", "nw": "north west", "se": "south east", "sw": "south west"}


def to_tikz(drawing, unit_cm=0.5, standalone=False):
    C = lambda p: f"({_f(p[0])},{_f(p[1])})"
    out = []
    if standalone:
        out += [r"\documentclass[tikz,border=4pt]{standalone}", r"\begin{document}"]
    if drawing.title:
        out.append(f"% {drawing.title}")
    out.append("% generated by diagen: every coordinate is resolved, edit the netlist instead")
    out.append(rf"\begin{{tikzpicture}}[x={unit_cm}cm, y=-{unit_cm}cm, line width=0.7pt, "
               r"line cap=round, line join=round, font=\small]")
    for p in drawing.prims:
        if isinstance(p, Line):
            opts = []
            if p.dashed:
                opts.append("dashed")
            if p.color:
                opts.append(p.color)
            if p.width != 1.0:
                opts.append(f"line width={_f(0.7 * p.width)}pt")
            o = f"[{', '.join(opts)}]" if opts else ""
            out.append(rf"\draw{o} " + " -- ".join(C(q) for q in p.pts) + ";")
        elif isinstance(p, Poly):
            cmd = r"\filldraw" if p.fill == "black" else (r"\filldraw[fill=white]" if p.fill == "white" else r"\draw")
            out.append(f"{cmd} " + " -- ".join(C(q) for q in p.pts) + " -- cycle;")
        elif isinstance(p, Circle):
            if p.fill == "black":
                cmd = r"\fill"
            elif p.fill == "white":
                cmd = r"\filldraw[fill=white]"
            else:
                cmd = r"\draw"
            out.append(f"{cmd} {C(p.c)} circle[radius={_f(p.r)}];")
        elif isinstance(p, Path):
            d = C(p.start)
            for c1, c2, e in p.segs:
                d += f" .. controls {C(c1)} and {C(c2)} .. {C(e)}"
            if p.closed:
                d += " -- cycle"
            cmd = r"\filldraw" if p.fill == "black" else r"\draw"
            out.append(f"{cmd} {d};")
        elif isinstance(p, Text):
            size = "" if p.size == 1.0 else (r", font=\footnotesize" if p.size >= 0.85 else r", font=\scriptsize")
            out.append(rf"\node[anchor={TIKZ_ANCHOR[p.anchor]}, inner sep=1pt{size}] at {C(p.pos)} "
                       f"{{{to_tex(p.s)}}};")
    out.append(r"\end{tikzpicture}")
    if standalone:
        out.append(r"\end{document}")
    return "\n".join(out) + "\n"
